services:
  msg-transformation:
    container_name: msg-transformation
    image: msg-transformation:${VERSION_MSG_TRANSFORMATION}
    labels:
      service.type: "app"
      service.description: "dnc"
    restart: always
    privileged: true
    ports:
      - '8081:8081'
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8081/ionweb/r/restapi/messagetransformation/openapi.json || exit 1"
      interval: 60s
      timeout: 5s
      start_period: 120s  
      retries: 3
    volumes:
      - ${PLATFORM_DIR}/msg-transformation/log:/opt/ion/platform/log
      - ${PLATFORM_DIR}/msg-transformation/daemon/DM/LOGS:/opt/ion/platform/daemon/DM/LOGS
      - ${PLATFORM_DIR}/msg-transformation/daemon/DM/log_archiver/LOGS:/opt/ion/platform/daemon/DM/log_archiver/LOGS
    env_file:
      - ${DNC_PACKAGE_DIR}/env-msg-transformation
    extra_hosts:
      - 'dockerci:127.0.0.1'
    hostname: ${HOSTNAME}
    stop_grace_period: 3m