services:
  ebics-mockserver:
    container_name: ebics-mockserver
    image: graudocreg01.reval.com:8092/reval/ebicsmockserver:${VERSION_EBICS_MOCKSERVER}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ebicsmocktest:/ebicstestserver/test
      - ebicsmockuserkey:/ebicstestserver/userkey
    ports:
      - 4443:4443
      - 4422:4422
      - 4480:4480
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:4480/ || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  bofa-mock:
    container_name: bofa-mock
    image: graudocreg01.reval.com:8092/reval/bofa-mock:${VERSION_BOFA_MOCK}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9085:9443
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9443/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  icas-mock:
    container_name: icas-mock
    image: graudocreg01.reval.com:8092/reval/icas-mock:${VERSION_ICAS_MOCK}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${MOCK_CONFIGDIR}/tenants.json:/itsconfig/tenants.json
      - ${MOCK_CONFIGDIR}/userTenantMapping.csv:/itsconfig/userTenantMapping.csv
      - ${MOCK_KEYSDIR}/icas:/icas
    ports:
      - 9075:9075
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --no-check-certificate --tries=1 --spider https://icas-mock:9075/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  citi-mock:
    container_name: citi-mock
    image: graudocreg01.reval.com:8092/reval/citi-mock:${VERSION_CITI_MOCK}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    environment:
      - key.citi.private.decryption.certificate=/citi/citiPrivateDecryptionCertificate.pem
      - key.citi.private.signing.certificate=/citi/citiPrivateSigningCertificate.pem
      - key.itg.public.signing.certificate=/citi/itgPublicSigningCertificate.pem
      - key.itg.public.encryption.certificate=/citi/itgPublicEncryptionCertificate.cert
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${MOCK_CONFIGDIR}/appconfig_CitiMock.xml:/itsconfig/appconfig.xml
      - ${MOCK_KEYSDIR}/citi:/citi
    ports:
      - 9095:9443
      - 9097:8080
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  itg-api-mock:
    container_name: itg-api-mock-server
    image: graudocreg01.reval.com:8092/reval/itg-api-mock-server:${VERSION_ITG_API_MOCK_SERVER}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    environment:
      - key.citi.private.decryption.certificate=/citi/citiPrivateDecryptionCertificate.pem
      - key.citi.private.signing.certificate=/citi/citiPrivateSigningCertificate.pem
      - key.itg.public.signing.certificate=/citi/itgPublicSigningCertificate.pem
      - key.itg.public.encryption.certificate=/citi/itgPublicEncryptionCertificate.cert
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${MOCK_CONFIGDIR}/appconfig_ItgApiMock.xml:/itsconfig/appconfig.xml
      - ${MOCK_CONFIGDIR}/mssql-jdbc-7.4.1.jre11.jar:/itsconfig/mssql-jdbc-7.4.1.jre11.jar
    ports:
      - 9088:8080
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  sftp-mock:
    container_name: sftp-mock
    image: graudocreg01.reval.com:8092/reval/sftp-mock:${VERSION_SFTP_MOCK}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    environment:
      - file.server.rootDir=/sftp
      - file.server.remoteDirectory=/sftp    
      - pgp.private.key=/keys/PGPPrivate.asc
      - pgp.public.key=/keys/PGPPublic.asc
      - ftps.server.keystoreFile=/keys/keystore.p12
      - ftps.server.truststoreFile=/keys/truststore.p12
      - sftp.server.enableStaticPasswordAuthenticator=false
      - sftp.server.publicKeyfile=/keys/sftpPublicKey.pub
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${MOCK_CONFIGDIR}/appconfig_SftpMock.xml:/itsconfig/appconfig.xml
      - ${MOCK_SFTPDIR}:/sftp
      - ${MOCK_KEYSDIR}/sftp:/keys
    ports:
      - 9089:9089
      - 9090:9090
      - 9086:9086
      - 9087:9087
      - 9081:9081
      - 9084:9084
      - 9093:9093
      - 9100:9100
      - 9101:9101
      - 9102:9102
      - 9103:9103
      - 9104:9104
      - 9105:9105
      - 9106:9106
      - 9107:9107
      - 9108:9108
      - 9109:9109
      - 9110:7089
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:7089/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  ibam-mock:
    container_name: ibam-mock
    image: graudocreg01.reval.com:8092/reval/ibam-mock:${VERSION_IBAM_MOCK}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${MOCK_CONFIGDIR}/appconfig_IbamMock.xml:/itsconfig/appconfig.xml
      - ${MOCK_KEYSDIR}/ibam:/ibam
    ports:
      - 9091:9443
      - 9092:8080
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  dnc-adapter-mock:
    container_name: dnc-adapter-mock
    image: graudocreg01.reval.com:8092/reval/dnc-adapter-mock:${VERSION_DNC_ADAPTER_MOCK}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9094:9443
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9443/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  sanctions-screening-mock:
    container_name: sanctions-screening-mock
    image: graudocreg01.reval.com:8092/reval/sanctions-screening-mock:${VERSION_SANCTIONS_SCREENING_MOCK}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9096:8080
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  hsbc-mock:
    container_name: hsbc-mock
    image: graudocreg01.reval.com:8092/reval/hsbc-mock:${VERSION_HSBC_MOCK}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9099:9099
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9099/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  opentext-mock:
    container_name: opentext-mock
    image: graudocreg01.reval.com:8092/reval/opentext-mock:${VERSION_OPENTEXT_MOCK}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9098:8080
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  jpmc-mock:
    container_name: jpmc-mock
    image: graudocreg01.reval.com:8092/reval/jpmc-mock:${VERSION_JPMC_MOCK}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${MOCK_CONFIGDIR}/appconfig_JpmcMock.xml:/itsconfig/appconfig.xml
      - ${MOCK_KEYSDIR}/jpmc:/jpmc
    ports:
      - 9111:9111
      - 9112:9112
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9111/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
  trustpair-mock:
    container_name: trustpair-mock
    image: graudocreg01.reval.com:8091/reval/trustpair-mock:${VERSION_TRUSTPAIR_MOCK}
    labels:
      service.type: "app"
      service.description: "mock"
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=file:/config/
      - SERVER_PORT=9293
      - THC_PATH=/actuator/health
      - THC_PORT=9293
      - THC_PATH=/actuator/health
      - MANAGEMENT_SERVER_PORT=9293
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - http_proxy=
      - https_proxy=  
    ports:
      - "9113:9293"
    volumes:
      - ${MOCK_CONFIGDIR}/application.properties:/config/application.properties
      - ${MOCK_CONFIGDIR}/trustpair:/trustpair
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 20s
      timeout: 5s
      start_period: 5s
      retries: 10
volumes:
  ebicsmocktest:
  ebicsmockuserkey: