services:
  scs-screening:
    container_name: scs-screening
    image: scs-screening:${VERSION_SCS_SCREENING}
    labels:
      service.type: "app"
      service.description: "dnc"
    restart: always
    privileged: true
    ports:
      - '8083:8081'
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8081/ionweb/r/restapi/sanctionsscreening/openapi.json || exit 1"
      interval: 60s
      timeout: 5s
      start_period: 120s  
      retries: 3
    volumes:
      - ${PLATFORM_DIR}/scs-screening/log:/opt/ion/platform/log
      - ${PLATFORM_DIR}/scs-screening/daemon/DM/LOGS:/opt/ion/platform/daemon/DM/LOGS
      - ${PLATFORM_DIR}/scs-screening/daemon/DM/log_archiver/LOGS:/opt/ion/platform/daemon/DM/log_archiver/LOGS
    env_file:
      - ${DNC_PACKAGE_DIR}/env-scs-screening
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    hostname: ${HOSTNAME}
    stop_grace_period: 3m
  scs-exceptions:
    container_name: scs-exceptions
    image: scs-exceptions:${VERSION_SCS_EXCEPTIONS}
    labels:
      service.type: "app"
      service.description: "dnc"
    restart: always
    privileged: true
    ports:
      - '8082:8081'
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8081/ionweb/r/restapi/sanctionsscreening/openapi.json || exit 1"
      interval: 60s
      timeout: 5s
      start_period: 120s  
      retries: 3
    volumes:
      - ${PLATFORM_DIR}/scs-exceptions/log:/opt/ion/platform/log
      - ${PLATFORM_DIR}/scs-exceptions/daemon/DM/LOGS:/opt/ion/platform/daemon/DM/LOGS
      - ${PLATFORM_DIR}/scs-exceptions/daemon/DM/log_archiver/LOGS:/opt/ion/platform/daemon/DM/log_archiver/LOGS
    env_file:
      - ${DNC_PACKAGE_DIR}/env-scs-exceptions
    extra_hosts:
      - 'dockerci:127.0.0.1'
    hostname: ${HOSTNAME}
    stop_grace_period: 3m